specVersion: 0.0.1
description: This is a subquery mapping all event extrinsic over polkadot network
repository: ''
schema: ./schema.graphql
network:
  endpoint: 'wss://rpc.polkadot.io/public-ws'
dataSources:
  - name: main
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBlock
          kind: substrate/BlockHandler
        - handler: handleEvent
          kind: substrate/EventHandler
        - handler: handleCall
          kind: substrate/CallHandler
